# Generated by Django 5.1.7 on 2025-03-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_web', '0002_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecanicos', to='api_web.oficina')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to='api_web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api_web.usuario')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api_web.oficina')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api_web.mecanico')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='api_web.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api_web.usuario')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api_web.oficina')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_web.servico')),
            ],
        ),
    ]
